#let i18n = (
  en: (
    date: "Date",
    eval: "Evaluation",
    exam: "Exam",
    exercises: "Exercises",
    fig: "Fig.",
    ho: "handed out by",
    item: "Item",
    lab: "Lab",
    lc: "version of",
    mark: "Mark",
    of: "of",
    on: "on",
    page: "Page",
    poi: "Points",
    sol: "solution",
    subtask: "subtask",
    tab: "Tab.",
    task: "Task",
    with: "with",
    regards: "Best regards,",
    chap: "Chapter",
    appendix: "Appendix",
    abstract: "Abstract",
    toc: "Contents",
    thanks: "Acknowledgements",
    solution: "Solution",
    solutions: "Solutions",
    solution-to: "Solution to",
    solution-on: "Solution on",
    summer-term: "Summer term",
    winter-term: "Winter term",
    lecture-notes: "Lecture notes for the course",
    workbook: "Exercises for the course",
    institute-iace: "Institute of Automation and Control Engineering",
  ),
  de: (
    date: "Datum",
    eval: "Bewertung",
    exam: "Klausur",
    exercises: "Übungsaufgaben",
    fig: "Abb.",
    ho: "ausgegeben von",
    item: "Element",
    lab: "Labor",
    lc: "in der Fassung vom",
    mark: "Note",
    of: "von",
    on: "am",
    page: "Seite",
    poi: "Punkte",
    sol: "Lösung",
    subtask: "Aufgabe",
    tab: "Tab.",
    task: "Aufgabe",
    with: "mit",
    regards: "Mit freundlichen Grüßen",
    chap: "Kapitel",
    appendix: "Anhang",
    abstract: "Abstract",
    toc: "Inhaltsverzeichnis",
    thanks: "Danksagung",
    solution: "Lösung",
    solutions: "Lösungen",
    solution-to: "Lösung zu",
    solution-on: "Lösung auf",
    summer-term: "Sommersemester",
    winter-term: "Wintersemester",
    lecture-notes: "Skriptum zur Lehrveranstaltung",
    workbook: "Übungsaufgaben zur Lehrveranstaltung",
    institute-iace: "Institut für Automatisierungs- und Regelungstechnik",
  )
)

#let months = (
  "Januar",
  "Februar",
  "März",
  "April",
  "Mai",
  "Juni",
  "Juli",
  "August",
  "September",
  "Oktober",
  "November",
  "Dezember",
)
