name: Deploy to GitHub Artifacts

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install fonts
        run: |
          sudo apt install -y ttf-bitstream-vera
          cd $(mktemp -d /tmp/script.XXXXXXX)
          TEMP_DIR=$(pwd)
          mkdir -p ~/.fonts
          wget https://github.com/adobe-fonts/source-code-pro/releases/download/2.042R-u%2F1.062R-i%2F1.026R-vf/OTF-source-code-pro-2.042R-u_1.062R-i.zip
          unzip OTF-source-code-pro-2.042R-u_1.062R-i.zip
          cp -f OTF/*.otf ~/.fonts/
          rm -rf OTF
          wget https://github.com/adobe-fonts/source-serif/releases/download/4.005R/source-serif-4.005_Desktop.zip
          unzip source-serif-4.005_Desktop.zip
          cp -f source-serif-4.005_Desktop/OTF/*.otf ~/.fonts/
          rm -rf source-serif-4.005_Desktop
          wget https://github.com/adobe-fonts/source-sans/releases/download/3.052R/OTF-source-sans-3.052R.zip
          unzip OTF-source-sans-3.052R.zip
          cp -f OTF/*.otf ~/.fonts/
          rm -rf OTF
          fc-cache -f -v
          rm -rf $TEMP_DIR

      - name: Setup typst
        uses: typst-community/setup-typst@v4
        with:
          typst-version: latest

      - name: Determine and check package metadata
        run: |
          . scripts/setup @local

      - name: Build Examples
        run: |
          mkdir -p build_output
          cd scripts/
          ./build_examples.sh
          for f in ../example/*.pdf; do mv "$f" "../build_output/bmim-$(basename "$f").pdf"; done

      - name: Upload Artifacts
        id: deployment
        uses: actions/upload-artifact@v4
        with:
          name: BMIM-Pdf
          path: build_output/

