name: Deploy to GitHub Artifacts

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install fonts
        run: |
          sudo apt update
          sudo apt install -y lmodern cm-super fonts-cmu

      - name: Setup typst
        uses: typst-community/setup-typst@v4
        with:
          typst-version: latest

      - name: Determine and check package metadata
        run: |
          . scripts/setup @local

      - name: Build Examples
        run: |
          mkdir -p build_output
          for file in `ls example/*.typ`; do
            ex=${file##*/}
            pdf=${ex%typ}pdf
            typst c ${file} --root ./
            mv ${file%typ}pdf build_output/bmim-${pdf}
          done

      - name: Upload Artifacts
        id: deployment
        uses: actions/upload-artifact@v4
        with:
          name: BMIM-Pdf
          path: build_output/

